### ISSUE TITLE
Editing Player Level for Different Save Slots

### ISSUE THREAD

**Issue by mthreer** [Cracko298/Generation-Zero-Save-Editing#1]
Hi,

I was trying to modify the player level for my character that is on save slot 3. So I followed your guide and modified the player level using offset '3AC' (Dec: 940), however this appears to modify the level for the character at save slot 1. Kudos btw! Easy to follow guide. 💯  But maybe its a good idea to add to the guide that this only works for save slot 1 however.

Do you have any idea of how to modify the player level for the other save slots? 🙏

**Comment by mthreer** [comment]
I found that [offset D3C is player level for slot 3](https://user-images.githubusercontent.com/1528384/230792283-0a06e99f-3087-4b5a-b472-f5c04c4a3934.png). I modified it to **39** and it appears to work while [in the menu](https://user-images.githubusercontent.com/1528384/230792087-dd3d3a9b-3527-4340-bc2d-520e82b24c1d.png). 

Off topic: As soon I jump into a game and kill something, my level reverts to lvl 10 000. I'm therefore thinking its an issue with experience points. Which says (negative) -2147483608 in the game, [inside the Team tab](https://user-images.githubusercontent.com/1528384/230791880-5789b317-9001-42f9-9dff-2cb0496518fb.png) 

This is what my level looks like at [offset D3C afterwards](https://user-images.githubusercontent.com/1528384/230791999-24942c31-eb0b-473a-adf2-e7ef2892c361.png)

**Comment by Cracko298** [comment]
Sorry about the late reply. 
Seems I have forgotten to add other world Save-Slots along with the guide. *Whoops.
So yes, you can edit your level another way *by modifying your amount of XP instead of the level.

I'm looking into it right now, as I type this message. Should be a few minutes.

**Comment by Cracko298** [comment]
Which world are you on and which character as well?
I might be able to calculate the difference in offsets, might be able to find similarities between each character and world.

**Comment by mthreer** [comment]
I'm on World 3 and Character 3 :)

**Comment by mthreer** [comment]
Wouldn't it actually be necessary to edit both XP and level, in order for the level to stick correctly? Say you're lvl 1 with 10 XP, and you edit it to be level 50 with 10 XP, and then you kill something, gaining 1 XP, wouldn't you level down in that case?

**Comment by Cracko298** [comment]
Yes, that is correct.
So I found out each Character Save is an offset of "0x4C8" away from each other.

The math I did was pretty simple. Taking the offset, you said it was at "0xD3C" and subtracting "0x4C8", which gives; World 2, Character 2.

So... "0xD3C - 0x990" which gives me the original; World 1 Character 1 "3AC".

We can use this to find the other World Character Level, XP, etc.

**Comment by Cracko298** [comment]
Yeah, seems like I really hadn't thought that through.
I was using some older documentation of how the Player stats had worked.
Seems like it doesn't or does but barely. I'll need to update the guide and correct this, as well as include the Offsets between Character files. 

Thanks for pointing this out.

**Comment by mthreer** [comment]
That would be awesome! I honestly have no idea how my character all of a sudden became 10 000 so I've been wanting to change that back to something more reasonable.

**Comment by Cracko298** [comment]
You got it, and what level where you, and what level do you want.

**Comment by mthreer** [comment]
I was around 52, thats perfectly fine :)

**Comment by Cracko298** [comment]
Ight, I'll start attempting to get level 53's EXP decimal/hex and get back to you within a hour or two.

Sorry for any inconvenience this will cause you.

**Comment by mthreer** [comment]
None caused! 👌

**Comment by Cracko298** [comment]
Sorry about the longer wait, I had something quite important happen that I couldn't have missed.

I found the Value for level 53. (UInt24) which is: "2118875". Set that as your EXP, in your case it starts at offset: "0xD38".
Make sure to set your Player level at offset "0xD3C" to something lower than 53 (UInt8), such as level 24 or something like that.

After applying this fix, kill an enemy or two then Exit and Save. your Save-Data should be fixed after reopening your Generation Zero Save.

![image](https://user-images.githubusercontent.com/78656905/230918867-5f5d8d0b-9b1c-4859-85a4-b99390063f90.png)
![image](https://user-images.githubusercontent.com/78656905/230921260-7709533e-0190-49a1-8503-d14783b93479.png)


Sorry again for the unannounced absence of me, and again I apologize for any inconvenience this may have caused you.

**Comment by Cracko298** [comment]
If you don't have any more questions, and if this fixes your problem. please close the issue apon reading this message and applying the fix.
If this doesn't fix your problem, we'll keep this Issue request open.

Thanks for the issue request, I'll be sure to add the fixes suggested in this issue.

**Comment by mthreer** [comment]
Resolved! Thanks. I followed your instructions with a slight difference. I had to null out the Int32 and UInt32 as well, by writing 0 and then inserting 2118875 into those fields as well. Otherwise my player would revert back to lvl 10 000 as Int32 never changed from -2147483608 and Uint32 also never changed from 2147483608 by just modifying UInt24. 

Thanks for this :)

**Comment by Cracko298** [comment]
> If you don't have any more questions, and if this fixes your problem. please close the issue apon reading this message and applying the fix. If this doesn't fix your problem, we'll keep this Issue request open.
> 
> Thanks for the issue request, I'll be sure to add the fixes suggested in this issue.

Normally HxD does it automatically, glad to see it resolved in your Favor.
